name: midnight_never_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  uuid: ^4.2.1
  bcrypt: ^1.1.3
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0 
  test: ^1.20.0 
  
flutter:
  fonts:
    - family: Bosk
      fonts:
        - asset: assets/fonts/Bosk.ttf

    - family: Balmy
      fonts:
        - asset: assets/fonts/Balmy.ttf  

    - family: Kirsty
      fonts:
        - asset: assets/fonts/Kirsty Rg.otf
  assets:
    - assets/images/
    - assets/images/mini_dungeons/
    - assets/images/pfp/
    - assets/logos/logos-google/
    - assets/icons/
  uses-material-design: true
