name: midnight_never_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  uuid: ^4.2.1
  bcrypt: ^1.1.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: 2.5.2
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^5.2.1
  flame: ^1.28.1
  logger: ^2.5.0
  flutter_bloc: 9.0.0 # Para gerenciar o estado
  equatable: ^2.0.5 # Para comparar objetos no BLoC
  rxdart: ^0.28.0
  bloc: 9.0.0
  get_it: 8.0.3
  dio: 5.8.0+1
  intl: 0.19.0
  sqflite: 2.4.2
  flutter_dotenv: 5.2.1
  # Helpful for geolocation
  geolocator: 13.0.3
  # Google maps
  google_maps_flutter: 2.12.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0 
  test: ^1.20.0 

flutter_launcher_icons:
  android: true
  image_path: "assets/logos/logo-aplicativo/LOGO-MEME.png"  # Caminho para a nova imagem do ícone
  adaptive_icon_background: "#ffffff"  # (Opcional) Cor de fundo para Android  
  
flutter:
  fonts:
    - family: Bosk
      fonts:
        - asset: assets/fonts/Bosk.ttf

    - family: Balmy
      fonts:
        - asset: assets/fonts/Balmy.ttf  

    - family: Kirsty
      fonts:
        - asset: assets/fonts/KirstyRg.otf
  assets:
    - assets/images/
    - assets/images/mini_dungeons/
    - assets/images/pfp/
    - assets/logos/logos-google/
    - assets/icons/
    - assets/audios/

  uses-material-design: true

  
